language: objective-c
os: osx
osx_image: xcode11.6
xcode_project: SMAUpdatesAvailable.xcodeproj
xcode_scheme: SMAUpdatesAvailable-Tests

install: gem install slather

stages:
  - name: ios11Testing
    if: branch = master
  - name: ios12Testing
    if: branch = master
  - iOS13Testing

jobs:
  include:
    - stage: ios11Testing
      script: 
        - xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY= PROVISIONING_PROFILE= GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,name=iPhone X,OS=11.4" -scheme "SMAUpdatesAvailable-Tests" test
        - slather
        - curl -s https://codecov.io/bash | bash -s - -v -f test-reports/cobertura.xml -X coveragepy -X gcov -X xcode

    - stage: ios12Testing
      script: 
        - xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY= PROVISIONING_PROFILE= GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,name=iPhone 8,OS=12.4" -scheme "SMAUpdatesAvailable-Tests" test
        - slather
        - curl -s https://codecov.io/bash | bash -s - -v -f test-reports/cobertura.xml -X coveragepy -X gcov -X xcode

    - stage: ios13Testing
      script: 
        - xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY= PROVISIONING_PROFILE= GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,name=iPhone 11,OS=13.6" -scheme "SMAUpdatesAvailable-Tests" test
        - slather
        - curl -s https://codecov.io/bash | bash -s - -v -f test-reports/cobertura.xml -X coveragepy -X gcov -X xcode